#!/bin/sh

# Env variables
BROWSERTOUSE="firefox --new-tab"

# nice little functions
viewpath () {
	echo $PATH | sed 's/:/\n/g'
}


csvcols () {
	column -t -s ',' $1	
}


longsearch () {
	ls -lhrta --color=auto *$1*
}


removeleading () {
	sed "s/^ *//g"
}


removetrailing () {
	sed "s/ *$//g"
}

removesurrounding () {
	sed -e "s/ *$//g" -e "s/^ *//g"
}

spacestonewlines () {
	sed 's/ /\n/g'
}


niceoutput () {
	seperator="$1"
	header="$2"
	file="$3"
	echo -e "$header\n$(cat $file)" | column -ts "$1" -o " $(printf '\u2503')"

}


hardwareusage () {
	vmstat -s
	free -m
}

top10mem () {
	ps -aux --sort=-%mem | head
}


recentlogins () {
	last | egrep "$(date | awk '{print $1, $2, $3}')|$(date -d "yesterday" | awk '{print $1, $2, $3}')"	

}


surroundregex () {
	sed -E "s/$1/$2\0$2/g"
}


userprocs () {
	if [[ $1 = "" ]]; then
		user=$(whoami)
	else
		user="$1"
	fi
	procsnum=$(ps -u $user | wc -l)
	threadsnum=$(ps -Tu $user | wc -l)
	echo "$user procs: $procsnum"
	echo "$user threads: $threadsnum"
}


histgrep () {
  local n_lines=10
  if [[ "$1" =~ ^[0-9]*$ ]]; then
    n_lines="$1"
    shift
  fi
  grep "$@" ~/.full_history | tail -n "$n_lines"
}


findservice () {
if [[ $1 = "" ]]; then
	echo "No string to search for provided"
	return 1
fi

echo "Systemctl info for $1 on $(hostname)"
echo "---------------------------------------"
echo "--- Running ---"
systemctl --type=service --state=running | grep -iE --color=auto "$1"
echo "---------------------------------------"
echo "--- All ---"
systemctl --type=service --all | grep -iE --color=auto "$1"
echo "---------------------------------------"
echo "--- Running ---"
systemctl list-unit-files | grep -iE --color=auto "$1"
echo "---------------------------------------"
}


downloadrfc () {
if [[ ! -d ~/rfc ]]; then
	echo "RFC directory doesn't exist, please create it at ~/rfc"
	return 0
fi
if wget --spider "https://www.rfceditor.org/rfc/rfc$1.txt" > /dev/null 2>&1; then
	wget -qcO ~/rfc/ "https://www.rfc-editor.org/rfc/rfc$1.txt"
fi
}


mansearch () {
# Requires fzf
if ! which fzf; then
	echo "fzf not installed, please install"
fi
man -k . | fzf | awk '{print $1}' | xargs man
}


manname () {
# Requires fzf
if ! which fzf; then
	echo "fzf not installed, please install"
fi
man -k . | fzf | awk '{print $1}' | xargs man
}


getrfcindex () {
	curl https://www.rfc-editor.org/rfc-index.txt | awk 'NR > 66' > $HOME/rfc/rfcindex.txt
}

searchrfcindex () {
	awk -v RS= -v FS="\(Format" '{sub(/\n/,"",$1);sub(/ {4,}/,"",$1);print $1}' $HOME/rfc/rfcindex.txt | fzf
}

webman () {
	$BROWSERTOUSE "https://manned.org/man/fedora-41/$1"
}


# Sed surround text in place
#	echo "testing100testing" | sed -E 's/[0-9]{3}/\(\0\)/g'
#

# Awk extract substring matching regex from string
#
#	echo "beans gmpd" | awk '{ match($0, /gmp.*$/); {print substr($0,RSTART,RLENGTH)}}'
#

# networking commands to use
#
# ping
# arping
# tracepath
# nmap
# ncat


