#!/bin/bash
sessionname="tmuxtest"
if tmux has-session -t "$sessionname" >/dev/null 2>&1; then
	exit
else
	# Create the new session
	tmux new-session -d -s "$sessionname"	
	# Rename the window
	tmux renamew "$sessionname"	
	# Select and split the panes
	tmux selectp -t 0
	tmux splitw -v -p 50
	tmux selectp -t 0
	tmux splitw -h -p 66
	tmux splitw -h -p 50
	tmux selectp -t 3
	tmux splitw -h -p 66
	tmux splitw -h -p 50
	# Run a command in each pane
	tmux send-keys -t 0 'echo 0' C-m
	tmux send-keys -t 1 'echo 1' C-m
	tmux send-keys -t 2 'echo 2' C-m
	tmux send-keys -t 3 'echo 3' C-m
	tmux send-keys -t 4 'echo 4' C-m
	tmux send-keys -t 5 'echo 5' C-m
	# Attach the session
	tmux attach -t "$sessionname"
fi
